window.courses = window.courses || [];
window.courses.push({
    name: "Pebble Beach Golf Links",
    par: 72,
    holes: [
        { number: 1, par: 4, distance: 380, fairwayWidth: 35, greenRadius: 16, greenType: "Back-to-Front", pinLocation: "Center", pinX: 0, pinY: 380, description: "A gentle dogleg right away from the lodge. Keep your drive left to avoid the fairway bunkers.", fairwayDescription: "Fairway bends right at 240 yards. Bunkers guard the right elbow.", hazards: [{type: "Bunker", distance: 240, depth: 20, width: 25, offset: 20}], landingZones: [{name: "Fairway Left", x: -10, y: 250, z: 0}], zones: [{name: "Fairway Left", x: -10, y: 250}] },
        { number: 2, par: 5, distance: 511, fairwayWidth: 40, greenRadius: 18, greenType: "Bowl", pinLocation: "Back-Left", pinX: -5, pinY: 511, description: "A reachable Par 5, but a deep barranca crosses the fairway short of the green.", fairwayDescription: "Generous fairway, but a trench crosses at 430 yards.", hazards: [{type: "Bunker", distance: 430, depth: 15, width: 60, offset: 0}], landingZones: [{name: "Layup Short", x: 0, y: 410, z: 0}], zones: [{name: "Layup Short", x: 0, y: 410}] },
        { number: 3, par: 4, distance: 390, fairwayWidth: 32, greenRadius: 15, greenType: "Left-to-Right", pinLocation: "Right", pinX: 6, pinY: 390, description: "A tight dogleg left toward the ocean.", hazards: [{type: "Bunker", distance: 220, depth: 30, width: 20, offset: -20}], landingZones: [{name: "Right Center", x: 8, y: 240, z: 0}], zones: [{name: "Right Center", x: 8, y: 240}] },
        { number: 4, par: 4, distance: 331, fairwayWidth: 30, greenRadius: 12, greenType: "Crowned", pinLocation: "Front", pinX: 0, pinY: 331, description: "A short Par 4. The ocean runs the entire length down the right side.", fairwayDescription: "Ocean hugs the right. Bunkers guard the left.", hazards: [{type: "Water", distance: 0, depth: 331, width: 200, offset: 120}], landingZones: [{name: "Green Approach", x: 0, y: 310, z: 0}], zones: [{name: "Green Approach", x: 0, y: 310}] },
        { number: 5, par: 3, distance: 192, fairwayWidth: 20, greenRadius: 14, greenType: "Tiered", pinLocation: "Center", pinX: 0, pinY: 192, description: "A stunning Par 3 hugging the coastline. The green is nestled right on the cliff's edge.", hazards: [{type: "Water", distance: 0, depth: 200, width: 200, offset: 110}], landingZones: [{name: "Safe Green Center", x: 0, y: 192, z: 0}], zones: [{name: "Safe Green Center", x: 0, y: 192}] },
        { number: 6, par: 5, distance: 511, fairwayWidth: 40, greenRadius: 16, greenType: "Back-to-Front", pinLocation: "Back-Right", pinX: 5, pinY: 511, pinZ: 15, description: "The famous uphill Par 5. The second shot plays steeply up the cliff face.", fairwayDescription: "Fairway runs along the ocean, then turns sharply uphill for the final 150 yards.", hazards: [{type: "Water", distance: 0, depth: 511, width: 200, offset: 120}], landingZones: [{name: "Base of the Cliff", x: 0, y: 360, z: 0}, {name: "Top of the Cliff", x: 0, y: 450, z: 12}], zones: [{name: "Base of the Cliff", x: 0, y: 360}, {name: "Top of the Cliff", x: 0, y: 450}] },
        { number: 7, par: 3, distance: 106, fairwayWidth: 10, greenRadius: 10, greenType: "Bowl", pinLocation: "Center", pinX: 0, pinY: 106, pinZ: -12, description: "One of the most photographed holes in the world. A tiny, steep downhill Par 3 completely surrounded by the Pacific Ocean.", hazards: [{type: "Water", distance: 90, depth: 50, width: 200, offset: 30}, {type: "Water", distance: 116, depth: 50, width: 200, offset: 0}, {type: "Water", distance: 90, depth: 50, width: 200, offset: -30}], landingZones: [{name: "Green Center", x: 0, y: 106, z: -12}], zones: [{name: "Green Center", x: 0, y: 106}] },
        { number: 8, par: 4, distance: 427, fairwayWidth: 35, greenRadius: 14, greenType: "Back-to-Front", pinLocation: "Right", pinX: 6, pinY: 427, description: "A blind tee shot up a hill, followed by an iconic approach shot over an ocean chasm to a tiny green.", fairwayDescription: "The fairway ends abruptly at a cliff at 240 yards. You must lay up to the edge.", hazards: [{type: "Water", distance: 245, depth: 140, width: 300, offset: 0}], landingZones: [{name: "Cliff Edge", x: 0, y: 235, z: 5}], zones: [{name: "Cliff Edge", x: 0, y: 235}] },
        { number: 9, par: 4, distance: 481, fairwayWidth: 30, greenRadius: 15, greenType: "Left-to-Right", pinLocation: "Center", pinX: 0, pinY: 481, description: "A brutal Par 4 with the ocean on the right and a fairway that severely slopes toward the water.", hazards: [{type: "Water", distance: 0, depth: 481, width: 200, offset: 110}], landingZones: [{name: "Fairway Left", x: -15, y: 260, z: 0, tilt: -2, slope: 0}], zones: [{name: "Fairway Left", x: -15, y: 260}] },
        { number: 10, par: 4, distance: 446, fairwayWidth: 32, greenRadius: 16, greenType: "Left-to-Right", pinLocation: "Back-Left", pinX: -5, pinY: 446, description: "Similar to 9, the ocean hugs the right side, demanding a precise drive to a sloping fairway.", hazards: [{type: "Water", distance: 0, depth: 446, width: 200, offset: 110}], landingZones: [{name: "Fairway Target", x: -10, y: 250, z: 0}], zones: [{name: "Fairway Target", x: -10, y: 250}] },
        { number: 11, par: 4, distance: 380, fairwayWidth: 35, greenRadius: 14, greenType: "Back-to-Front", pinLocation: "Center", pinX: 0, pinY: 380, description: "Turning away from the ocean, an uphill approach to a tiny, heavily bunkered green.", hazards: [{type: "Bunker", distance: 360, depth: 15, width: 15, offset: -10}, {type: "Bunker", distance: 360, depth: 15, width: 15, offset: 10}], landingZones: [{name: "Fairway Target", x: 0, y: 230, z: 0}], zones: [{name: "Fairway Target", x: 0, y: 230}] },
        { number: 12, par: 3, distance: 201, fairwayWidth: 20, greenRadius: 17, greenType: "Bowl", pinLocation: "Center", pinX: 0, pinY: 201, description: "A long Par 3 guarded by a deep bunker short and left.", landingZones: [{name: "Green Center", x: 0, y: 201, z: 0}], zones: [{name: "Green Center", x: 0, y: 201}] },
        { number: 13, par: 4, distance: 403, fairwayWidth: 35, greenRadius: 16, greenType: "Back-to-Front", pinLocation: "Center", pinX: 0, pinY: 403, description: "An uphill Par 4. The approach favors a high, soft iron.", landingZones: [{name: "Fairway Target", x: 0, y: 250, z: 0}], zones: [{name: "Fairway Target", x: 0, y: 250}] },
        { number: 14, par: 5, distance: 572, fairwayWidth: 40, greenRadius: 18, greenType: "Tiered", pinLocation: "Back-Left", pinX: -6, pinY: 572, pinZ: 8, description: "A monster Par 5 dogleg right. The green is elevated and guarded by a massive bunker complex.", hazards: [{type: "Bunker", distance: 540, depth: 25, width: 40, offset: 0}], landingZones: [{name: "Dogleg Corner", x: 15, y: 280, z: 0}, {name: "Layup Zone", x: 0, y: 450, z: 2}], zones: [{name: "Dogleg Corner", x: 15, y: 280}, {name: "Layup Zone", x: 0, y: 450}] },
        { number: 15, par: 4, distance: 397, fairwayWidth: 35, greenRadius: 15, greenType: "Bowl", pinLocation: "Center", pinX: 0, pinY: 397, description: "A straightforward Par 4 heading back toward the ocean.", landingZones: [{name: "Fairway Target", x: 0, y: 240, z: 0}], zones: [{name: "Fairway Target", x: 0, y: 240}] },
        { number: 16, par: 4, distance: 401, fairwayWidth: 35, greenRadius: 16, greenType: "Left-to-Right", pinLocation: "Center", pinX: 0, pinY: 401, description: "A slight dogleg right. Avoid the fairway bunker on the right to have a clean look at the green.", landingZones: [{name: "Fairway Left", x: -10, y: 250, z: 0}], zones: [{name: "Fairway Left", x: -10, y: 250}] },
        { number: 17, par: 3, distance: 177, fairwayWidth: 15, greenRadius: 12, greenType: "Hourglass", pinLocation: "Back-Left", pinX: -5, pinY: 177, description: "A legendary Par 3 with a figure-eight shaped green surrounded by bunkers. The ocean awaits anything long or left.", hazards: [{type: "Bunker", distance: 160, depth: 15, width: 30, offset: 0}, {type: "Water", distance: 185, depth: 50, width: 200, offset: -20}], landingZones: [{name: "Green Center", x: 0, y: 177, z: 0}], zones: [{name: "Green Center", x: 0, y: 177}] },
        { number: 18, par: 5, distance: 543, fairwayWidth: 45, greenRadius: 18, greenType: "Left-to-Right", pinLocation: "Front-Right", pinX: 5, pinY: 543, description: "The most famous finishing hole in golf. The ocean crashes along the entire left side, and a lone Cypress tree guards the fairway.", fairwayDescription: "A gorgeous curving fairway. The ocean is immediately left. A massive tree sits directly in the center of the fairway at 260 yards.", hazards: [{type: "Water", distance: 0, depth: 543, width: 200, offset: -120}], trees: [{name: "The Famous Cypress", x: 0, y: 260, radius: 8, height: 18}], landingZones: [{name: "Right of the Tree", x: 15, y: 250, z: 0}, {name: "Safe Layup", x: 10, y: 420, z: 0}], zones: [{name: "Right of the Tree", x: 15, y: 250}, {name: "Safe Layup", x: 10, y: 420}] }
    ]
});
